import { escapeHtml } from "./util.js";

/** Render an SBOM as SPDX 2.3 tag-value text. */
export function formatSpdx(sbom) {
  const lines = [
    "SPDXVersion: SPDX-2.3",
    "DataLicense: CC0-1.0",
    "SPDXID: SPDXRef-DOCUMENT",
    `DocumentName: ${sbom.metadata.component.name}`,
    "DocumentNamespace: https://github.com/stealth-alpha/fathom/spdx/" +
      (sbom.serialNumber || "document"),
    `Creator: Tool: fathom-cli-0.1.0`,
    "Created: " + new Date().toISOString(),
    "",
  ];
  sbom.components.forEach((comp, i) => {
    const id = `SPDXRef-Package-${i}`;
    lines.push(`PackageName: ${comp.name}`);
    lines.push(`SPDXID: ${id}`);
    if (comp.version) lines.push(`PackageVersion: ${comp.version}`);
    lines.push(`PackageSupplier: Organization: Unknown`);
    lines.push("PackageDownloadLocation: NOASSERTION");
    lines.push("PackageVerificationCode: NOASSERTION");
    lines.push(`LicenseConcluded: ${comp.licenses[0]?.license?.id || comp.licenses[0]?.license?.name || "NOASSERTION"}`);
    lines.push("PackageLicenseDeclared: " + (comp.licenses[0]?.license?.id || comp.licenses[0]?.license?.name || "NOASSERTION"));
    lines.push(`ExternalRef: PACKAGE-MANAGER purl ${comp.purl}`);
    lines.push("Relationship: SPDXRef-DOCUMENT DESCRIBES " + id);
    lines.push("");
  });
  return lines.join("\n");
}

/** Render a human-friendly license/compliance report as Markdown. */
export function formatLicensesMarkdown(sbom, config = {}) {
  const lines = [];
  lines.push("# Dependency & License Report", "");
  lines.push(
    `Generated by Fathom for **${sbom.metadata.component.name}**. ` +
      `Inventory covers **${sbom.components.length}** components.`
  );
  lines.push("");

  const byLicense = new Map();
  for (const comp of sbom.components) {
    const lic =
      comp.licenses[0]?.license?.id || comp.licenses[0]?.license?.name || "UNKNOWN";
    if (!byLicense.has(lic)) byLicense.set(lic, []);
    byLicense.get(lic).push(comp);
  }

  lines.push("## Summary by license", "");
  lines.push("| License | Count |", "| --- | --- |");
  for (const [lic, comps] of [...byLicense.entries()].sort()) {
    lines.push(`| ${lic} | ${comps.length} |`);
  }
  lines.push("");

  if (sbom.summary?.violations?.length) {
    lines.push("## Policy findings", "");
    for (const v of sbom.summary.violations) {
      lines.push(
        `- **${v.severity.toUpperCase()}** — ${v.component}${
          v.version ? `@${v.version}` : ""
        } (${v.license}): ${v.message}`
      );
    }
    lines.push("");
  }

  lines.push("## Components", "");
  lines.push("| Name | Version | Type | License |", "| --- | --- | --- | --- |");
  for (const comp of sbom.components) {
    const lic =
      comp.licenses[0]?.license?.id || comp.licenses[0]?.license?.name || "UNKNOWN";
    lines.push(
      `| ${comp.name} | ${comp.version || "—"} | ${comp.purl.split("/")[0]} | ${lic} |`
    );
  }
  lines.push("");
  return lines.join("\n");
}

/** Minimal HTML for the embedded SBOM page. */
export function formatSbomHtml(sbom) {
  const dirs = sbom.components.reduce((acc, comp) => {
    const lic =
      comp.licenses[0]?.license?.id || comp.licenses[0]?.license?.name || "UNKNOWN";
    acc[lic] = (acc[lic] || 0) + 1;
    return acc;
  }, {});
  const rows = sbom.components
    .map((comp) => {
      const lic =
        comp.licenses[0]?.license?.id || comp.licenses[0]?.license?.name || "UNKNOWN";
      return (
        `<tr><td>${escapeHtml(comp.name)}</td><td><code>${escapeHtml(
          comp.version || "—"
        )}</code></td><td>${escapeHtml(lic)}</td><td><code>${escapeHtml(
          comp.purl
        )}</code></td></tr>`
      );
    })
    .join("\n");
  const summary = Object.entries(dirs)
    .map(
      ([lic, count]) =>
        `<span class="stat">${escapeHtml(lic)} <strong>${count}</strong></span>`
    )
    .join("");
  return `
<section class="sbom">
  <h2>Dependency Inventory</h2>
  <p class="lead">${sbom.components.length} components across ${
    Object.keys(dirs).length
  } licenses.</p>
  <div class="stats">${summary}</div>
  <div class="table-wrap"><table>
    <thead><tr><th>Name</th><th>Version</th><th>License</th><th>Package URL</th></tr></thead>
    <tbody>${rows}</tbody>
  </table></div>
</section>`;
}
